services:
  - type: web
    name: cpfreezetag
    env: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
